#!/bin/sh
readonly AGENTDIR="/opt/aws/amazon-cloudwatch-agent"
readonly CMDDIR="${AGENTDIR}/bin"
readonly CONFDIR="${AGENTDIR}/etc"

# The systemd and upstart scripts assume exactly this .toml file name
readonly TOML="${CONFDIR}/amazon-cloudwatch-agent.toml"
readonly JSON="${CONFDIR}/amazon-cloudwatch-agent.json"
readonly COMMON_CONIG="${CONFDIR}/common-config.toml"

set -e

#if [ ! -f "${JSON}" ]; then
#    ${CMDDIR}/config-downloader --output-file ${JSON} --download-source "default" --mode "auto" --config ${COMMON_CONIG} || exit 1
#fi
#${CMDDIR}/config-translator --input ${JSON} --output ${TOML} --mode "auto" --config ${COMMON_CONIG} || exit 2
exec ${CMDDIR}/amazon-cloudwatch-agent -pidfile ${AGENTDIR}/var/amazon-cloudwatch-agent.pid -config ${CONFDIR}/amazon-cloudwatch-agent.toml
